spring.application.name=production-optimizer
spring.profiles.active=dev

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=admin-projedata
spring.datasource.password=admin-projedata

spring.jpa.database-plataform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.defer-datasource-initialization=true

spring.h2.console.path=/h2
spring.h2.console.enabled=true
